---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "dependabot: [github-actions] "
      include: scope

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "dependabot: [npm] "
      include: "scope"

  - package-ecosystem: nuget
    directory: "/"
    groups:
      microsoft:
        patterns:
          - Microsoft*
      nunit:
        patterns:
          - NUnit*
    ignore:
      - dependency-name: "Microsoft*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "NUnit*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
    commit-message:
      prefix: "dependabot: [nuget] "
