---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependencies(github-actions): "

  - package-ecosystem: nuget
    directory: "/"
    groups:
      microsoft:
        patterns:
          - Microsoft*
        update-types: ["minor", "patch"]
      testing:
        patterns:
          - xunit*
        update-types: ["minor", "patch"]
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependencies(nuget): "

  - package-ecosystem: nuget
    directory: /examples/SaanSoft.Cqrs.Example.InMemory.Api
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/SaanSoft.Cqrs
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/SaanSoft.Tests.Cqrs
    schedule:
      interval: daily
