---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "22:30"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependabot(github-actions): "
      include: scope

  - package-ecosystem: nuget
    directory: "/"
    groups:
      microsoft:
        patterns:
          - Microsoft*
      nunit:
        patterns:
          - NUnit*
    ignore:
      - dependency-name: "NUnit*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
      time: "22:40"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependabot(nuget): "
