---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependencies(github-actions): "

  - package-ecosystem: nuget
    directory: "/"
    groups:
      microsoft:
        patterns:
          - Microsoft*
        update-types: ["minor", "patch"]
      testing:
        patterns:
          - NUnit*
          - xunit*
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "NUnit*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
      time: "12:20"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependencies(nuget): "
