on: workflow_call

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: test-changed-files
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all changed c# files
        id: changed-csharp-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.cs

      - name: List all changed files c# files
        if: steps.changed-csharp-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-csharp-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "- $file"
          done

      - name: Lint c# files
        if: steps.changed-csharp-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-csharp-files.outputs.all_changed_files }}
        run: |
          chmod +x ./scripts/lint-dotnet.sh
          ./scripts/lint-dotnet.sh "${ALL_CHANGED_FILES}" --verify-no-changes --report reports/dotnet-format-report.json

      - name: Archive unit test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: dotnet-format-errors
          path: reports

