name: build-and-test

on:
  pull_request:
    paths-ignore:
      - '.husky/**'
      - '.idea/**'
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '.husky/**'
      - '.idea/**'
      - '**.md'

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}-${{matrix.dotnet-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet-version: ['6.0', '7.0', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-restore --configuration Release --filter FullyQualifiedName~SaanSoft.Tests --logger "trx;LogFileName=unit-test-results.trx" --results-directory reports

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.dotnet-version }}
          path: reports

  test-reports:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ always() }}
    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dotnet test results
        uses: actions/download-artifact@v4
        with:
          path: reports

      - name: Upload test report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: test-results                    # Name of the check run which will be created
          path: "reports/test-results-*/*.trx"  # Path to test results (inside artifact .zip)
          reporter: dotnet-trx                  # Format of test results
          fail-on-error: true
