name: ci-cd

on:
  pull_request:
    paths-ignore:
      - '.githooks/**'
      - '.idea/**'
      - '.vs/**'
      - '.vscode/**'
      - '**.dic'
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths:
      - 'src/**'

permissions:
  checks: write

jobs:
  build-and-test:
    uses: ./.github/workflows/_build_and_test.yml
  upload-reports:
    uses: ./.github/workflows/_report_test_results.yml
    needs: build-and-test
    if: success() || failure()
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
