name: dependabot-validate

on:
  pull_request:
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/dependabot-validate.yml"

jobs:
  dependabot-validate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: validate dependabot
        uses: marocchino/validate-dependabot@v3

