name: Dependabot auto update branch from main

on: pull_request

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    # Checking the author and fork will prevent your Action run failing on non-Dependabot PRs
    if: |
      github.event.repository.fork == false &&
      github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          PR_FILTER: "labelled"
          PR_LABELS: "dependencies"
