name: dependabot-validate

on:
  pull_request:
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/dependabot-validate.yml"

jobs:
  dependabot-validate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: validate dependabot
        uses: marocchino/validate-dependabot@d8ae5c0d03dd75fbd0ad5f8ab4ba8101ebbd4b37 # v3.0.0

