name: lint

on: pull_request

permissions:
  contents: read

jobs:
  super-linter:
    runs-on: ubuntu-latest

    permissions:
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Get changed c# files
        id: changed-csharp-files
        uses: tj-actions/changed-files@20576b4b9ed46d41e2d45a2256e5e2316dde6834 # v43.0.1
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.cs

      - name: Setup linting config
        id: config
        run: |
          if [ "${hasChangedCSharpFiles}" == "true" ]; then
            echo "VALIDATE_ALL_CODEBASE=false" >> "$GITHUB_OUTPUT"
          else
            echo "VALIDATE_ALL_CODEBASE=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          hasChangedCSharpFiles: ${{ steps.changed-csharp-files.outputs.any_changed == 'true' }}

      - name: Run super-linter
        uses: super-linter/super-linter@92e2606383320f72e6129f8a50d8537cf9c84ed6 # v6.3.1
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (./\.editorconfig|\.idea/*|\.vscode/*)
          IGNORE_GENERATED_FILES: true
          # false -> only checks changed files
          VALIDATE_ALL_CODEBASE: ${{ steps.config.outputs.VALIDATE_ALL_CODEBASE  == 'true'}}
          VALIDATE_CSHARP: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_YAML: true

  spellcheck:
    permissions:
      contents: read  # for streetsidesoftware/cspell-action to fetch files for commit
      pull-requests: read  # for streetsidesoftware/cspell-action to fetch commits for PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@ca4bb065dd09aca9c90c935f7dc9bb625985226c # v6.1.0
        with:
          config: .cspell.json
          check_dot_files: false
          incremental_files_only: true

